# Generated by Django 6.0.1 on 2026-02-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_tag_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='books.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
