# Generated by Django 6.0.1 on 2026-02-03 13:24

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_tags_alter_tag_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[books.validators.RangeValidator(max_value=100, message='Price must be between 0 and 100', min_value=0)]),
        ),
    ]
